# Site settings
title: Good Clean Read
tag_text: Good Clean Read
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "https://adueck.github.io/good-clean-read"
baseurl: "/good-clean-read"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
